# Config file for Jalpc theme

# Website settings
title:       Mauricio C치ceres Bravo
description: Mauricio C치ceres Bravo's personal site.
keywords:    Mauricio Caceres,Mauricio Caceres Bravo,blog,Jalpc,github,gh-pages
baseurl:     /beta                            # If you have suburl as homepage, like '/homepage', change to '/homepage'
url:         http://mcaceresb.github.io/beta  # url should be changed to custom name if applicable
img_path:    /beta/static/assets/img/blog     # url should be changed to '/homepage/static/assets/img/blog' as before

# Author -- index page "about me" section
author:  # change following line to your infomation.
  name:              Mauricio C치ceres Bravo # Be used at blog posts' author.
  first_name:        Mauricio               # Be used at index page about me section.
  last_name:         C치ceres Bravo          # Be used at index page about me section.
  cv:                https://mcaceresb.github.io/assets/cv.pdf # Link to CV; leave blank if you don't have
  email:             mauricio.caceres.bravo@gmail.com      # Leave blank if you don't have now
  medium_username:   mcaceresb                             # Leave blank if you don't have now
  github_username:   mcaceresb                             # Leave blank if you don't have now
  avatar:            /static/assets/img/landing/avatar.jpg # Upload your avatar and edit it.
  skill_icon1:
    - name:          icon-python
    - name:          fa-line-chart
  skill_icon2:
    - name:          fa-linux
    - name:          fa-code
  desc:              Hi! I am a research assistant based in Cambridge, MA. This is my personal website, meant to force myself to speed along some coding projects I've had in the back-burner throughout the past year.

# Comment
disqus:  # Go to https://disqus.com/ to configure comments; ow comment out
  # name: jalpc
  # public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# Analytics
## google analytics
ga:  # Go to https://www.google.com/analytics/ to configure; ow comment out
  id: UA-91854317-1

## GrowingIO
gio:  # Go to https://www.growingio.com/ to configure; ow comment out
  # id:

## Donation
donation: off  # 'on'/'off' to display donation button at post page

# Build settings
encoding: utf-8

# Other settings
highlighter: rouge
# highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
  # syntax_highlighter: pygments
  syntax_highlighter: rouge
